// 原稿md（../原稿/）とスクショ（../スクショ/）から静的サイトを生成する。
// 実行: node build.mjs  （依存パッケージなし・Node 22）
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, copyFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename } from 'node:path';
import { parsePage, parseSlides } from './md.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, '..', '原稿');
const SHOTS = { pc: join(here, '..', 'スクショ', 'pc'), sp: join(here, '..', 'スクショ', 'smartphone') };
const IMG = join(here, 'assets', 'img');

// 原稿の参照名 → 実ファイル名（前方一致で探すので番号だけでも当たる）
const ALIAS = {
  'chatgpt_project_create.png': 'chatgpt_01',
  'chatgpt_project_instructions.png': 'chatgpt_02',
  'chatgpt_project_files.png': 'chatgpt_03',
  'claude_project_create.png': 'claude_01',
  'claude_project_instructions.png': 'claude_02',
  'claude_project_knowledge.png': 'claude_03',
  'gemini_gem_create.png': 'gemini_01',
  'gemini_gem_instructions.png': 'gemini_02',
  'gemini_gem_files.png': 'gemini_03',
};

const used = [];
const missing = [];

function findFile(ref) {
  const stem = ALIAS[ref];
  for (const dir of [SHOTS.pc, SHOTS.sp]) {
    if (!existsSync(dir)) continue;
    const files = readdirSync(dir).filter((f) => f.endsWith('.png'));
    if (stem) {
      const hit = files.find((f) => f.startsWith(stem));
      if (hit) return join(dir, hit);
    }
    if (files.includes(ref)) return join(dir, ref);
    const loose = files.find((f) => f === ref || f.startsWith(ref.replace('.png', '')));
    if (loose) return join(dir, loose);
  }
  return null;
}

function size(path) {
  const out = execFileSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', path]).toString();
  return {
    w: Number(out.match(/pixelWidth:\s*(\d+)/)[1]),
    h: Number(out.match(/pixelHeight:\s*(\d+)/)[1]),
  };
}

// スクショを assets/img/ に置く（幅1200px超なら縮小。元ファイルは触らない）
function shot(ref, depth) {
  const src = findFile(ref);
  if (!src) {
    if (!missing.includes(ref)) missing.push(ref);
    return null;
  }
  const name = basename(src);
  const dest = join(IMG, name);
  if (!existsSync(dest)) {
    copyFileSync(src, dest);
    if (size(dest).w > 1200) execFileSync('sips', ['--resampleWidth', '1200', dest]);
  }
  const dim = size(dest);
  if (!used.some((u) => u.file === name)) used.push({ ref, file: name, w: dim.w, h: dim.h });
  return { src: `${depth}assets/img/${name}`, w: dim.w, h: dim.h };
}

const head = (title, depth, css) => `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>${title}</title>
<link rel="stylesheet" href="${depth}assets/${css}">`;

function pageTitle(title) {
  if (title === 'AI×暮らし ― 自分専用の「暮らしのカルテ」をつくる2時間') {
    return '<span>AI×暮らし</span><span>自分専用の</span><span>「暮らしのカルテ」をつくる</span>';
  }
  if (title === 'AI×暮らし ― AIに毎回貼るのを、そろそろやめませんか') {
    return '<span>AI×暮らし</span><span>AIに毎回貼るのを、</span><span>そろそろやめませんか</span>';
  }
  return esc(title);
}

function slideTitle(title) {
  if (title === 'AI×暮らし ― 自分専用の「暮らしのカルテ」をつくる2時間') {
    return '<span>AI×暮らし</span><span>自分専用の</span><span>「暮らしのカルテ」をつくる</span><span>2時間</span>';
  }
  if (title === 'AI×暮らし ― AIに毎回貼るのを、そろそろやめませんか') {
    return '<span>AI×暮らし</span><span>AIに毎回貼るのを、</span><span>そろそろやめませんか</span>';
  }
  return esc(title);
}

function herbArt() {
  return `<svg class="hero-art" viewBox="0 0 620 190" aria-hidden="true" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M15 176C108 153 113 95 179 98C235 101 235 156 284 145C334 134 315 62 386 62C448 62 459 123 605 20" stroke="currentColor" stroke-width="2"/>
  <path d="M120 130C82 116 72 92 82 68C107 79 124 98 120 130Z" fill="currentColor"/>
  <path d="M225 122C188 108 176 78 184 54C214 62 235 89 225 122Z" fill="currentColor"/>
  <path d="M338 104C366 72 402 69 421 86C398 109 367 116 338 104Z" fill="currentColor"/>
  <path d="M484 92C503 59 538 51 562 66C543 94 514 103 484 92Z" fill="currentColor"/>
  <circle cx="286" cy="145" r="4" fill="#B77D67"/><circle cx="386" cy="62" r="4" fill="#B77D67"/>
</svg>`;
}

function pageHtml(doc, depth, slidesHref) {
  return `<!-- generated by build.mjs -->
${head(doc.title, depth, 'site.css')}
<a class="skip" href="#s1">本文へ</a>
<header class="top">
<div class="top-inner">
<p class="brand">AI LABORATORY</p>
<h1>${pageTitle(doc.title)}</h1>
<p class="sub">${doc.subtitle}</p>
<a class="slides-link" href="${slidesHref}">スライドを見る</a>
</div>
${herbArt()}
</header>
<main>
${doc.html}
</main>
<footer class="foot"><p>${doc.footer}</p></footer>
<script src="${depth}assets/site.js"></script>
`;
}

function slidesHtml(title, slides, depth) {
  const n = slides.length;
  const renderedSlides = slides.map((slide, i) =>
    i === 0 ? slide.replace(/<h2>[\s\S]*?<\/h2>/, `<h2 class="slide-title">${slideTitle(title)}</h2>`) : slide
  );
  return `<!-- generated by build.mjs -->
${head(title, depth, 'slides.css')}
<div class="stage-wrap"><div class="stage" id="stage">
${renderedSlides.join('\n')}
<div class="num"><span id="cur">1</span> / ${n}</div>
</div></div>
<p class="hint">→ ← Space で送る・f で全画面</p>
<script src="${depth}assets/slides.js"></script>
`;
}

function build(slug, pageMd, slideMd) {
  const depth = '../';
  const doc = parsePage(readFileSync(join(SRC, pageMd), 'utf8'), (ref) => shot(ref, depth));
  mkdirSync(join(here, slug), { recursive: true });
  writeFileSync(join(here, slug, 'index.html'), pageHtml(doc, depth, `slides/`));
  const slides = parseSlides(readFileSync(join(SRC, slideMd), 'utf8'));
  mkdirSync(join(here, slug, 'slides'), { recursive: true });
  writeFileSync(join(here, slug, 'slides', 'index.html'), slidesHtml(doc.title, slides, '../../'));
  return { slug, copy: doc.counts.copy, tabs: doc.counts.tabs, slides: slides.length };
}

mkdirSync(IMG, { recursive: true });
const r1 = build('shokyu', '初級_配布ページ.md', '初級_スライド.md');
const r2 = build('chukyu', '中級_配布ページ.md', '中級_スライド.md');

writeFileSync(
  join(here, 'index.html'),
  `<!-- generated by build.mjs -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title></title>
`
);
writeFileSync(join(here, 'robots.txt'), 'User-agent: *\nDisallow: /\n');
writeFileSync(join(here, '.nojekyll'), '');
writeFileSync(join(here, 'README.md'), '配布用の静的ページ。`node build.mjs` で `../原稿/` から生成する。\n');

console.log(JSON.stringify({ pages: [r1, r2], used, missing }, null, 2));
